# Generated by Django 3.1.6 on 2021-02-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
